# Generated by Django 4.1 on 2022-08-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 1', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 1',
                'verbose_name_plural': 'Задание 1',
            },
        ),
        migrations.CreateModel(
            name='Task10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 10',
                'verbose_name_plural': 'Задания 10',
            },
        ),
        migrations.CreateModel(
            name='Task11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 11',
                'verbose_name_plural': 'Задания 11',
            },
        ),
        migrations.CreateModel(
            name='Task12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 12',
                'verbose_name_plural': 'Задания 12',
            },
        ),
        migrations.CreateModel(
            name='Task13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 13',
                'verbose_name_plural': 'Задания 13',
            },
        ),
        migrations.CreateModel(
            name='Task14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 14',
                'verbose_name_plural': 'Задания 14',
            },
        ),
        migrations.CreateModel(
            name='Task15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 15',
                'verbose_name_plural': 'Задания 15',
            },
        ),
        migrations.CreateModel(
            name='Task16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 16',
                'verbose_name_plural': 'Задания 16',
            },
        ),
        migrations.CreateModel(
            name='Task17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 17',
                'verbose_name_plural': 'Задания 17',
            },
        ),
        migrations.CreateModel(
            name='Task18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 18',
                'verbose_name_plural': 'Задания 18',
            },
        ),
        migrations.CreateModel(
            name='Task19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 19',
                'verbose_name_plural': 'Задания 19',
            },
        ),
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 2',
                'verbose_name_plural': 'Задание 2',
            },
        ),
        migrations.CreateModel(
            name='Task20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 20',
                'verbose_name_plural': 'Задания 20',
            },
        ),
        migrations.CreateModel(
            name='Task21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 21',
                'verbose_name_plural': 'Задания 21',
            },
        ),
        migrations.CreateModel(
            name='Task22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 22',
                'verbose_name_plural': 'Задания 22',
            },
        ),
        migrations.CreateModel(
            name='Task23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 23',
                'verbose_name_plural': 'Задания 23',
            },
        ),
        migrations.CreateModel(
            name='Task24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 24',
                'verbose_name_plural': 'Задания 24',
            },
        ),
        migrations.CreateModel(
            name='Task25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 25',
                'verbose_name_plural': 'Задания 25',
            },
        ),
        migrations.CreateModel(
            name='Task26',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 26',
                'verbose_name_plural': 'Задания 26',
            },
        ),
        migrations.CreateModel(
            name='Task27',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 27',
                'verbose_name_plural': 'Задания 27',
            },
        ),
        migrations.CreateModel(
            name='Task3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 3',
                'verbose_name_plural': 'Задания 3',
            },
        ),
        migrations.CreateModel(
            name='Task4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 4',
                'verbose_name_plural': 'Задания 4',
            },
        ),
        migrations.CreateModel(
            name='Task5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 5',
                'verbose_name_plural': 'Задания 5',
            },
        ),
        migrations.CreateModel(
            name='Task6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 6',
                'verbose_name_plural': 'Задания 6',
            },
        ),
        migrations.CreateModel(
            name='Task7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 7',
                'verbose_name_plural': 'Задания 7',
            },
        ),
        migrations.CreateModel(
            name='Task8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 8',
                'verbose_name_plural': 'Задания 8',
            },
        ),
        migrations.CreateModel(
            name='Task9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Задание 2', max_length=100)),
                ('content', models.TextField(blank=True, verbose_name='Задание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото к заданию')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл к заданию')),
            ],
            options={
                'verbose_name': 'Задание 9',
                'verbose_name_plural': 'Задания 9',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('task1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task1')),
                ('task10', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task10')),
                ('task11', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task11')),
                ('task12', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task12')),
                ('task13', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task13')),
                ('task14', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task14')),
                ('task15', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task15')),
                ('task16', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task16')),
                ('task17', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task17')),
                ('task18', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task18')),
                ('task19', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task19')),
                ('task2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task2')),
                ('task20', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task20')),
                ('task21', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task21')),
                ('task22', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task22')),
                ('task23', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task23')),
                ('task24', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task24')),
                ('task25', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task25')),
                ('task26', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task26')),
                ('task27', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task27')),
                ('task3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task3')),
                ('task4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task4')),
                ('task5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task5')),
                ('task6', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task6')),
                ('task7', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task7')),
                ('task8', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task8')),
                ('task9', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.task9')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
    ]
